default_platform(:android)

platform :android do
    desc "Submit a new Beta Build to Crashlytics Beta"
    gradle(
        task: 'assemble',
        build_type: 'Release'
    )
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:95816973391:android:1c8b8225140c5b7a4f7e3a",
            firebase_cli_path: "/usr/local/bin/firebase",
            apk_path: "../build/app/outputs/apk/release/app-release.apk",
            groups: "all"
        )
    end
end
